name: Hello World Workflow
on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello, World!
        run: echo "Hello, World!"

      - name: Print Hello, World! using GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Hello, World!");

